# Generated by Django 3.0.7 on 2020-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.FloatField(),
        ),
    ]
